[project]
name = "workbench"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["Cython~=3.0.11", "torch~=2.5.1", "numpy~=2.2.1"]

[dependency-groups]
dev = ["pytest~=8.3.4"]
lint = ["ruff~=0.8.6", "mypy~=1.14.1"]
